import "./globals.css";
// import { Inter } from "next/font/google";
import Sidebar from "./component/Sidebar";
import { personalData } from "@/data/pageData";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="flex flex-col sm:flex-row">
                <Sidebar data={personalData} />
                <main className="grow-full p-8 sm:p-16 w-full sm:basis-2/3  ml-auto bg-cyan-50">
                    {children}
                </main>
            </body>
        </html>
    );
}
